from __future__ import annotations

from enum import StrEnum


class PageKind(StrEnum):
    TES_ADMINISTRATIVO = "TES_ADMINISTRATIVO"
    EQUIPES_EXECUCAO = "EQUIPES_EXECUCAO"
    PLANO_MANOBRA = "PLANO_MANOBRA"
    PASSOS_MANOBRA = "PASSOS_MANOBRA"
    CROQUI_RESUMIDO = "CROQUI_RESUMIDO"
    PROJETO_REDE = "PROJETO_REDE"
    DETALHE_TECNICO = "DETALHE_TECNICO"
    ANEXO_DESCONHECIDO = "ANEXO_DESCONHECIDO"
    UNKNOWN = "UNKNOWN"


class JobStatus(StrEnum):
    UPLOADED = "UPLOADED"
    CLASSIFYING_PAGES = "CLASSIFYING_PAGES"
    EXTRACTING = "EXTRACTING"
    PARSING = "PARSING"
    BUILDING_GRAPH = "BUILDING_GRAPH"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    GENERATING = "GENERATING"
    DONE = "DONE"
    FAILED = "FAILED"


class Severity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
